version: 2.1
jobs:
  test:
    machine: true
    working_directory: ~/kglib
    steps:
      - checkout
      - run:
          name: Bazel - Install
          command: |
           curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
           chmod +x bazel-0.20.0-installer-linux-x86_64.sh
           sudo ./bazel-0.20.0-installer-linux-x86_64.sh
      - run: echo "Bazel installed"
      - run: bazel test //:ordered_test

workflows:
  version: 2
  kglib:
    jobs:
      - test